name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Python ${{ matrix.python-version }} • ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Ubuntu-only: install EGL/OpenGL + Xvfb for headless rendering
      - name: Install system libs (Linux only)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libegl1 \
            libgl1 \
            libopengl0 \
            libglu1-mesa \
            libxrandr2 \
            libxinerama1 \
            libxcursor1 \
            libxi6 \
            xvfb

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        shell: bash

      - name: Install package
        run: |
          pip install -e .
        shell: bash

      - name: Run tests (macOS/Windows)
        run: |
          pytest -q
        shell: bash
